--drop table if exists userinfo cascade;
--
--create table userinfo (
--	id integer generated by default as AUTO_INCREMENT,
--	password varchar(255),
--	role varchar(255) array,
--	username varchar(255),
--	primary key (id)
--);

INSERT INTO userinfo (password ,role,username) VALUES ('password',ARRAY ['USER','ADMIN'],'jignesh');
INSERT INTO userinfo (password ,role,username) VALUES ('password123',ARRAY ['ADMIN'],'dipak');